# -*- coding: utf-8 -*-
"""ParantapGuha_MinorProject-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ft5idAGOvw9sOdX8GcOXWS38NSb9ggO9

#COMPREHENSIVE EXPLORATORY DATA ANALYSIS

**Dataset Source:** https://www.kaggle.com/datasets/winterbreeze/fifa19eda

##1. ENVIRONMENT SETUP AND DATA LOADING

###1.1 Setting up Kaggle and downloading the dataset
"""

from google.colab import files
files.upload() # uploading the kaggle.json file

#relocating the kaggle.json file
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

# Downloading the dataset directly from kaggle
!kaggle datasets download -d winterbreeze/fifa19eda

# Unzipping the downloaded file
!unzip -o fifa19eda.zip

"""###1.2 Loading important libaries and the dataset"""

# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Loading the dataset
df = pd.read_csv('fifa_eda.csv')

# Displaying the first 10 rows
df.head(10)

"""## 2. STRUCTURAL INSPECTION

###2.1 Checking data types and memory usage
"""

print("--- Dataframe Info ---")
df.info()

"""There are `18` features, among which `6` are categorical (`object`) and `12` are numerical (`int64`,`float64`) features in this dataset.

###2.2 Descriptive statistics for all numerical columns
"""

print("\n--- Descriptive Statistics ---")
df.describe()

"""###2.3 Reporting the number of rows and features in the dataset"""

print(f"Dataset Shape: {df.shape[0]} tuples, {df.shape[1]} features\n")

"""###2.4 Listing all the names of the features present in the dataset"""

print("Columns in Dataset:")
columns=df.columns
for column in columns:
    print(f"- {column}")

"""## 3. DATA CLEANING (The Preprocessing Phase)

###3.1 Missing Value Analysis

Identifying if any features contain `null` values to prevent model errors and determine if we need to drop or impute using `mean`, `median` or `mode`.
"""

print("Missing values per column:\n")
df.isnull().sum()

"""As we can see there are missing values present in `club`, `Value`, `International Reputation`, `Skill Moves`, `Contract Valid Until` columns. Among which `club` and `Contract Valid Until` are categorical and others are numerical.

So, we are separating the numerical and categorical columns into `num_cols` and `cat_cols` respectively.
"""

num_cols = df.select_dtypes(include=['int64','float64']).columns
cat_cols = df.select_dtypes(include=['object']).columns

"""As there are `200` to `300` null values in a `18000` tuple dataset. Null values comprise less than `2%` of the data so we can easily handle them without disturbing the pattern of data.
- `Value`,`International Reputation`, `Skill Moves` are numerical columns and can be filled in with `mean`.
- `club` and `Contract Valid Until` are both categorical columns and have unpredictable values so we will drop them instead of filling them up using `mode`.
"""

df[num_cols]=df[num_cols].fillna(df[num_cols].mean())
df.dropna(subset=['Club', 'Contract Valid Until'], inplace=True)

print("Total Missing values in the dataset after cleaning: ",df.isnull().sum().sum(),"\n")

"""There are `0` null values in the dataset showing that we have successfully dealt with them.

###3.2 Duplicate Handling

Removing duplicate entries to ensure our analysis and subsequent models are not biased by redundant data.

Checking for duplicate rows in the dataset
"""

duplicate_count = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_count}")

"""As we can see there are no duplicates in the dataset so we wont be dropping them."""

if duplicate_count > 0:
    df = df.drop_duplicates()
    print("Duplicates removed successfully.")
else :
    print("No duplicates found in the dataset.")

"""###3.3 Data Type Correction

Enforcing proper data types (like converting objects to categories or datetimes) optimizes memory and enables correct plotting/modeling.

We are focusing on `Contract Valid Until` as the values in the dataset are in the specific format of `datetime`. Also we need to change the data type of all `object` columns to `category`.
"""

for column in df.columns:
    if column == 'Contract Valid Until' or column == 'Joined':
        df[column] = pd.to_datetime(df[column])
        print(f"Converted '{column}' column to datetime type.")
    elif df[column].dtype == 'object':
        df[column] = df[column].astype('category')
        print(f"Converted '{column}' column to category type.")

"""Cross checking if all the datatypes of columns have changed"""

print("\nUpdated Data Types:")
print(df.dtypes)

"""## 4. UNIVARIATE ANALYSIS

###4.1 Numerical Feature Distribution

We use histograms and boxplots to visualize the distribution, check for skewness, and spot potential outliers.
"""

num_cols = df.select_dtypes(include=[np.number], exclude=['datetime', 'datetime64']).columns
for col in num_cols:
    plt.figure(figsize=(12, 5))

    plt.subplot(1, 2, 1)
    sns.histplot(df[col].dropna(), kde=True, color='royalblue')
    plt.title(f'Distribution of {col}')

    plt.subplot(1, 2, 2)
    sns.boxplot(y=df[col].dropna(), color='orchid')
    plt.title(f'Boxplot of {col} (Outlier Detection)')

    plt.tight_layout()
    plt.show()

"""*  `ID` - It is a unique value given to each footballer so the skewness and the presence of **outliers** is justified.
*  `Age` - Age is slightly **right-skewed**, indicating a higher proportion of younger players compared to older veterans. There are **outliers** present in this feature which are to be dealt with. Might need standardisation/normalisation before using it in modelling.
*  `Overall`,`Potential`,`Height` and `Weight` - All are normally distributed but there are many **outliers** present which need to be dealt with.
*  `Value`,`Wage` and `Release Clause` - These are heavily **right-skewed** showing majority of the players have low net worth and are less paid. This shows many players surely have started their career as a footballer but very few reach the top. There is presence of many **outliers** which need to be dealt with. These three features also follow the same trend so might be **collinear** to each other.
*  `International Reputation` and `Skill Moves` - These two features are player ratings from 1 to 5. Both are **slightly right-skewed** like other features. There are **class imbalances** and **outliers** as well.

###4.2 Categorical Feature Frequency

Visualizing class frequencies helps identify class imbalances which is crucial for machine learning tasks.
"""

top_10_values = df['Nationality'].value_counts().head(10)

plt.figure(figsize=(10, 8))
ax = sns.barplot(x=top_10_values.values, y=top_10_values.index.astype(str), hue=top_10_values, palette='plasma')
for container in ax.containers:
    ax.bar_label(container, padding=3)
plt.title('Top 10 Nationalities with the most players in FIFA 19')
plt.xlabel('Number of Players')
plt.ylabel('Nationality')
plt.tight_layout()
plt.show()

"""Here, we can get a glimpse of the countries which produce the most number of football players mentioning names like `England`, `Germany`, `Spain`, `Argentina` and `France`."""

df['Club'].value_counts().head(20)

"""Here, we can see that `Club` has a lot of `value_counts` so there is no use of trying to find the club which have the most players."""

plt.figure(figsize=(8, 5))
ax=sns.countplot(x='Preferred Foot', data=df, hue='Preferred Foot', palette='viridis')
for container in ax.containers:
    ax.bar_label(container, padding=2)
plt.title('Frequency of Preferred Foot')
plt.show()

"""We can clearly see the class imbalance of **left-footed** and **right-footed** players."""

plt.figure(figsize=(14, 6))
position_order = df['Position'].value_counts().index
ax = sns.countplot(x='Position', data=df, hue='Position', palette='plasma',
                   order=position_order, legend=False)
for container in ax.containers:
    ax.bar_label(container, padding=2)
plt.title('Frequency of Player Positions in FIFA 19')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""We can clearly notice that among a lot of positions in which the players play in, the most chosen or most popular are `ST` (Striker), `GK` (GoalKeeper) and `CB` (Center Back).

## 5. BIVARIATE & MULTIVARIATE ANALYSIS

###5.1 Correlation Matrix

Evaluating linear relationships between numerical features to find strong dependencies and screen for multi-collinearity.
"""

corr_matrix = df.select_dtypes(include=[np.number]).corr()

sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title('Numerical Feature Correlation Matrix')
plt.show()

"""###5.2 Scatter Plots

Checking specific relationships between two highly correlated numerical variables.
"""

# 1. Overall vs. Potential
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Overall', y='Potential', data=df, alpha=0.6, color='dodgerblue')
plt.title('Player Overall Rating vs. Potential Rating')
plt.xlabel('Overall Rating')
plt.ylabel('Potential Rating')
# Adding a reference line where Overall = Potential
plt.plot([40, 95], [40, 95], color='red', linestyle='--', linewidth=1.5, label='Max Potential Reached')
plt.legend()
plt.tight_layout()
plt.show()

"""Firstly `Overall` and `Potential` show a positive linear relationship as expected. Here we can see that all players have much more potential than their overall rating."""

# 2. Wage vs. Value
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Value', y='Wage', data=df, alpha=0.5, color='mediumseagreen')
plt.title('Player Transfer Value vs. Weekly Wage')
plt.xlabel('Value (in Euros)')
plt.ylabel('Wage (in Euros)')
plt.tight_layout()
plt.show()

"""As we previously saw, `Value` and `Wage` are **linearly related** and their individual distribution being **right skewed** is clearly visible in the plot as well."""

# 3. Height vs. Weight
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Height', y='Weight', data=df, alpha=0.5, color='darkorange')
plt.title('Physical Attributes: Height vs. Weight')
plt.xlabel('Height')
plt.ylabel('Weight')
plt.tight_layout()
plt.show()

"""`Height` and `Weight` follow a strict positive relationship and hence might not add much value to the model if both are included. Might need feature engineering.

###5.3 Grouped Box Plots

Observing how numerical values vary across different categorical groups to identify distinguishing features.
"""

plt.figure(figsize=(12, 8))
position_order = df.groupby('Position', observed=False)['Overall'].median().sort_values(ascending=False).index
sns.boxplot(x='Overall', y='Position', data=df, hue='Position', order=position_order, palette='viridis', legend=False)
plt.title('Distribution of Overall Ratings by Player Position')
plt.xlabel('Overall Rating')
plt.ylabel('Position')
plt.tight_layout()
plt.show()

"""If we notice the `median` of ratings in each `boxplot` of positions. The highest median Overall ratings are given to `RAM` (Right-Attacking MidFielder), `LF` (Left Forward), `LAM` (Left-Attacking MidFielder) and `RF` (Right Forward). These positions are responsible for creativity and impact in the matches they play in. So, overall rating is not just influenced by the performance but also the creativity and chances created."""

# 2. Wage by Preferred Foot
plt.figure(figsize=(8, 5))
sns.boxplot(x='Preferred Foot', y='Wage', data=df, hue='Preferred Foot', palette='Set2')
plt.title('Wage Distribution by Preferred Foot')
plt.xlabel('Preferred Foot')
plt.ylabel('Wage (in Euros)')
plt.tight_layout()
plt.show()

"""The `median` of both the `Left` and `Right` footed players are same. So, irrespective of the foot they play in, their wages do not appear to be dependent on their preferred foot."""

# 3. Potential by Top 10 Nationalities (Sorted by Median)
top_10_countries = df['Nationality'].value_counts().head(10).index
df_top_10 = df[df['Nationality'].isin(top_10_countries)].copy()
df_top_10['Nationality'] = df_top_10['Nationality'].astype(str)

median_order = df_top_10.groupby('Nationality')['Potential'].median().sort_values(ascending=False).index

plt.figure(figsize=(10, 8))
sns.boxplot(
    x='Potential',
    y='Nationality',
    data=df_top_10,
    hue='Nationality',
    order=median_order,
    palette='mako',
    legend=False,
    dodge=False
)
plt.title('Player Potential Across Top 10 Nationalities (Sorted by Median)')
plt.xlabel('Potential Rating')
plt.ylabel('Nationality')
plt.tight_layout()
plt.show()

"""Even though `England` and `Germany` were the top two countries to provide the most football players, they do not necessarily guarantee the highest median potential for their players. On the other hand `Spain` and `Argentina` are the two countries having the most talented players.

## 6. Final Summary & Insights

###6.1 Key Takeaways

1. **Extreme Financial Skewness**: The distributions for `Value`, `Wage`, and `Release Clause` are heavily right-skewed. The vast majority of players earn a baseline wage, while a select few superstar outliers command astronomically higher financial figures, stretching the distribution significantly.  

2. **Predictive Power of Categorical Features**: A player's categorical attributes heavily influence their ceiling. For instance, specific creative roles (like `LAM` , `RAM` , and `LF`) tend to have higher median `Overall` ratings , and nations like `Spain` and `Argentina` boast distinctly higher median potentials compared to other top-producing countries.  

3. **High Multicollinearity Risk**: The correlation matrix and scatter plots reveal strict linear relationships between certain features. Specifically, `Height` vs. `Weight`  and `Value` vs. `Release Clause` are almost perfectly correlated, providing redundant information.

###6.2 Model-Readiness Assessment

While the dataset is structurally sound with null values handled and data types corrected, it requires standard preprocessing before being fed into a machine learning algorithm:

1. **Feature Scaling**: Financial features (like `Wage`) operate on a massive scale compared to performance metrics (like `Overall` which caps at 99). A scaler (such as StandardScaler) must be applied to ensure distance-based models evaluate features equally.

2. **Categorical Encoding**: Algorithms require numerical input. `Preferred Foot` requires **Label Encoding** (`0` and `1`), while high-cardinality features like `Position` and `Nationality` require **One-Hot Encoding** to avoid implying a false mathematical hierarchy.

3. **Feature Selection**: To optimize model performance and prevent multicollinearity (especially for algorithms like `Naive Bayes` or `SVMs`), redundant features such as `Release Clause` and `Weight` should likely be dropped prior to training.
"""